In [1]:
import pandas as pd
import numpy as np
import cv2 as cv
import os
from scipy import stats
from PIL import Image
import matplotlib.pyplot as plt

In [2]:
os.getcwd()

'C:\\Users\\hp\\Python_conda'

Joao df for 100 files with four down scales and average for each row at each size

In [5]:
os.chdir(r"C:\Users\hp\Videos\Step1-fixedDistance_avg,std\Folders\2016-11-22-14-09-37-Joao_onlythermalthermal_image-txt")

In [66]:
joao_files = []  #Joao 

for idx,file in enumerate(os.listdir()):
    with open(file,encoding="utf8", errors='ignore')as f:
        text_file = np.loadtxt(f)
        text_file[text_file<32.0]=0
        text_file[text_file>37.0]=0
        cam_res1 = cv.resize(text_file, (191,144), interpolation = cv.INTER_NEAREST)
        
        #print(np.max(cam_res1), np.min(cam_res1[cam_res1 != 0 ]))
        
        
        cam_res2 = cv.resize(cam_res1, (95,72), interpolation = cv.INTER_NEAREST)
        cam_res3 = cv.resize(cam_res2, (32,24), interpolation = cv.INTER_NEAREST)
        #rint(np.max(cam_res3), np.min(cam_res3[cam_res3 != 0 ]))
        """"
        plt.imshow(text_file,cmap='jet')
        plt.show()
        plt.imshow(cam_res1,cmap='jet')
        plt.show()
        plt.imshow(cam_res2,cmap='jet')
        plt.show()
        plt.imshow(cam_res3,cmap='jet')
        plt.show()
        print()
        """
        
        joao_files.append({"file_name":file,
                              "AvgTemp(382,288)": np.average(text_file[text_file != 0]),
                              "AvgTemp(191,144)": np.average(cam_res1[cam_res1 != 0]),
                              "AvgTemp(95,72)": np.average(cam_res2[cam_res2 != 0]),
                              "AvgTemp(32,24)": np.average(cam_res3[cam_res3 != 0])})
        
    
    if idx == 99:
        break

In [67]:
df_joao = pd.DataFrame(joao_files, columns = ['file_name', "AvgTemp(382,288)","AvgTemp(191,144)","AvgTemp(95,72)","AvgTemp(32,24)"])

In [68]:
pd.set_option('max_rows', 99)
df_joao

,file_name,"AvgTemp(382,288)","AvgTemp(191,144)","AvgTemp(95,72)","AvgTemp(32,24)"
0,thermal_20161122-14_13_46.750.txt,34.363804,34.362176,34.401961,34.595062
1,thermal_20161122-14_13_46.785.txt,34.343402,34.345606,34.383567,34.489024
2,thermal_20161122-14_13_46.824.txt,34.340241,34.342957,34.358650,34.517284
3,thermal_20161122-14_13_46.860.txt,34.358668,34.358059,34.401266,34.545679
4,thermal_20161122-14_13_46.896.txt,34.348433,34.353717,34.388511,34.535000
...,...,...,...,...,...
95,thermal_20161122-14_13_50.572.txt,34.308287,34.320829,34.353314,34.334177
96,thermal_20161122-14_13_50.608.txt,34.310669,34.323435,34.353247,34.327848
97,thermal_20161122-14_13_50.647.txt,34.310501,34.326230,34.376890,34.307595
98,thermal_20161122-14_13_50.722.txt,34.310970,34.317014,34.338516,34.262500
99,thermal_20161122-14_13_50.757.txt,34.319824,34.321256,34.335971,34.332000

In [69]:
df_joao

,file_name,"AvgTemp(382,288)","AvgTemp(191,144)","AvgTemp(95,72)","AvgTemp(32,24)"
0,thermal_20161122-14_13_46.750.txt,34.363804,34.362176,34.401961,34.595062
1,thermal_20161122-14_13_46.785.txt,34.343402,34.345606,34.383567,34.489024
2,thermal_20161122-14_13_46.824.txt,34.340241,34.342957,34.358650,34.517284
3,thermal_20161122-14_13_46.860.txt,34.358668,34.358059,34.401266,34.545679
4,thermal_20161122-14_13_46.896.txt,34.348433,34.353717,34.388511,34.535000
...,...,...,...,...,...
95,thermal_20161122-14_13_50.572.txt,34.308287,34.320829,34.353314,34.334177
96,thermal_20161122-14_13_50.608.txt,34.310669,34.323435,34.353247,34.327848
97,thermal_20161122-14_13_50.647.txt,34.310501,34.326230,34.376890,34.307595
98,thermal_20161122-14_13_50.722.txt,34.310970,34.317014,34.338516,34.262500
99,thermal_20161122-14_13_50.757.txt,34.319824,34.321256,34.335971,34.332000

In [70]:
df_joao

,file_name,"AvgTemp(382,288)","AvgTemp(191,144)","AvgTemp(95,72)","AvgTemp(32,24)"
0,thermal_20161122-14_13_46.750.txt,34.363804,34.362176,34.401961,34.595062
1,thermal_20161122-14_13_46.785.txt,34.343402,34.345606,34.383567,34.489024
2,thermal_20161122-14_13_46.824.txt,34.340241,34.342957,34.358650,34.517284
3,thermal_20161122-14_13_46.860.txt,34.358668,34.358059,34.401266,34.545679
4,thermal_20161122-14_13_46.896.txt,34.348433,34.353717,34.388511,34.535000
...,...,...,...,...,...
95,thermal_20161122-14_13_50.572.txt,34.308287,34.320829,34.353314,34.334177
96,thermal_20161122-14_13_50.608.txt,34.310669,34.323435,34.353247,34.327848
97,thermal_20161122-14_13_50.647.txt,34.310501,34.326230,34.376890,34.307595
98,thermal_20161122-14_13_50.722.txt,34.310970,34.317014,34.338516,34.262500
99,thermal_20161122-14_13_50.757.txt,34.319824,34.321256,34.335971,34.332000

In [11]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(df_joao)

                            file_name  AvgTemp(382,288)  AvgTemp(144,191)  \
0   thermal_20161122-14_09_37.471.txt         34.457331         34.474038
1   thermal_20161122-14_09_37.646.txt         34.449913         34.454828
2   thermal_20161122-14_09_37.718.txt         34.459315         34.461408
3   thermal_20161122-14_09_37.756.txt         34.464809         34.474037
4   thermal_20161122-14_09_37.791.txt         34.460108         34.467482
5   thermal_20161122-14_09_37.829.txt         34.484951         34.496765
6   thermal_20161122-14_09_37.867.txt         34.472160         34.483547
7   thermal_20161122-14_09_37.910.txt         34.480368         34.495039
8   thermal_20161122-14_09_37.944.txt         34.492041         34.509054
9   thermal_20161122-14_09_37.978.txt         34.496598         34.508894
10  thermal_20161122-14_09_38.016.txt         34.496400         34.498727
11  thermal_20161122-14_09_38.051.txt         34.503695         34.510163
12  thermal_20161122-14_09_38.088.txt         34.484489         34.488219
13  thermal_20161122-14_09_38.125.txt         34.477584         34.489922
14  thermal_20161122-14_09_38.164.txt         34.485516         34.494023
15  thermal_20161122-14_09_38.201.txt         34.495171         34.497005
16  thermal_20161122-14_09_38.242.txt         34.512229         34.520336
17  thermal_20161122-14_09_38.277.txt         34.489864         34.492974
18  thermal_20161122-14_09_38.310.txt         34.510139         34.514474
19  thermal_20161122-14_09_38.349.txt         34.496499         34.498410
20  thermal_20161122-14_09_38.385.txt         34.496011         34.502910
21  thermal_20161122-14_09_38.423.txt         34.492056         34.498333
22  thermal_20161122-14_09_38.459.txt         34.479916         34.483476
23  thermal_20161122-14_09_38.496.txt         34.500203         34.503192
24  thermal_20161122-14_09_38.535.txt         34.505200         34.509616
25  thermal_20161122-14_09_38.574.txt         34.513208         34.517221
26  thermal_20161122-14_09_38.610.txt         34.519295         34.525308
27  thermal_20161122-14_09_38.647.txt         34.501547         34.509021
28  thermal_20161122-14_09_38.682.txt         34.513629         34.524062
29  thermal_20161122-14_09_38.720.txt         34.497026         34.507038
30  thermal_20161122-14_09_38.756.txt         34.510028         34.513846
31  thermal_20161122-14_09_38.794.txt         34.503797         34.521792
32  thermal_20161122-14_09_38.830.txt         34.513402         34.518369
33  thermal_20161122-14_09_38.869.txt         34.526294         34.536322
34  thermal_20161122-14_09_38.906.txt         34.488229         34.495078
35  thermal_20161122-14_09_38.942.txt         34.518151         34.533911
36  thermal_20161122-14_09_38.977.txt         34.496140         34.500316
37  thermal_20161122-14_09_39.015.txt         34.486862         34.504051
38  thermal_20161122-14_09_39.054.txt         34.513833         34.519173
39  thermal_20161122-14_09_39.090.txt         34.501915         34.516454
40  thermal_20161122-14_09_39.126.txt         34.494924         34.510572
41  thermal_20161122-14_09_39.166.txt         34.514742         34.531063
42  thermal_20161122-14_09_39.201.txt         34.487509         34.502918
43  thermal_20161122-14_09_39.238.txt         34.498276         34.508503
44  thermal_20161122-14_09_39.274.txt         34.514928         34.528546
45  thermal_20161122-14_09_39.310.txt         34.494319         34.498068
46  thermal_20161122-14_09_39.350.txt         34.484809         34.484850
47  thermal_20161122-14_09_39.385.txt         34.505296         34.508973
48  thermal_20161122-14_09_39.422.txt         34.517724         34.521631
49  thermal_20161122-14_09_39.465.txt         34.516341         34.517335
50  thermal_20161122-14_09_39.500.txt         34.504426         34.511837
51  thermal_20161122-14_09_39.537.txt         34.525928         34.537807
52  thermal_20161122-14_09_39.570.txt         34.503633         34.511192
53  thermal_20161122-14_09_39.607.txt         34.499143         34.496982
54  thermal_20161122-14_09_39.645.txt         34.504127         34.514163
55  thermal_20161122-14_09_39.685.txt         34.500735         34.497921
56  thermal_20161122-14_09_39.718.txt         34.495625         34.504803
57  thermal_20161122-14_09_39.760.txt         34.507930         34.502435
58  thermal_20161122-14_09_39.793.txt         34.504912         34.509638
59  thermal_20161122-14_09_39.834.txt         34.490226         34.497856
60  thermal_20161122-14_09_39.867.txt         34.493004         34.496404
61  thermal_20161122-14_09_39.904.txt         34.495914         34.510955
62  thermal_20161122-14_09_39.940.txt         34.504578         34.512899
63  thermal_20161122-14_09_39.977.txt         34.502491         34.500407
64  thermal_20161122-14_09_40.016.txt         34.492378         34.501040
65  thermal_20161122-14_09_40.056.txt         34.502741         34.508192
66  thermal_20161122-14_09_40.091.txt         34.532225         34.536339
67  thermal_20161122-14_09_40.130.txt         34.490642         34.492408
68  thermal_20161122-14_09_40.167.txt         34.488271         34.494779
69  thermal_20161122-14_09_40.200.txt         34.508469         34.509152
70  thermal_20161122-14_09_40.238.txt         34.506157         34.507717
71  thermal_20161122-14_09_40.275.txt         34.490852         34.486801
72  thermal_20161122-14_09_40.311.txt         34.506062         34.512690
73  thermal_20161122-14_09_40.349.txt         34.491896         34.494604
74  thermal_20161122-14_09_40.388.txt         34.501340         34.488217
75  thermal_20161122-14_09_40.426.txt         34.506246         34.518654
76  thermal_20161122-14_09_40.461.txt         34.508137         34.510144
77  thermal_20161122-14_09_40.501.txt         34.521733         34.529401
78  thermal_20161122-14_09_40.533.txt         34.529434         34.531820
79  thermal_20161122-14_09_40.572.txt         34.488810         34.495389
80  thermal_20161122-14_09_40.607.txt         34.500454         34.504798
81  thermal_20161122-14_09_40.644.txt         34.523109         34.527901
82  thermal_20161122-14_09_40.686.txt         34.532812         34.545581
83  thermal_20161122-14_09_40.722.txt         34.520128         34.527730
84  thermal_20161122-14_09_40.755.txt         34.509202         34.516489
85  thermal_20161122-14_09_40.792.txt         34.518566         34.527142
86  thermal_20161122-14_09_40.834.txt         34.493212         34.501521
87  thermal_20161122-14_09_40.866.txt         34.512618         34.512599
88  thermal_20161122-14_09_40.904.txt         34.535368         34.533717
89  thermal_20161122-14_09_40.940.txt         34.521508         34.520395
90  thermal_20161122-14_09_40.980.txt         34.519046         34.534565
91  thermal_20161122-14_09_41.021.txt         34.538591         34.532278
92  thermal_20161122-14_09_41.056.txt         34.540820         34.550935
93  thermal_20161122-14_09_41.088.txt         34.529253         34.543203
94  thermal_20161122-14_09_41.125.txt         34.511441         34.517320
95  thermal_20161122-14_09_41.166.txt         34.521962         34.523156
96  thermal_20161122-14_09_41.201.txt         34.525755         34.537173
97  thermal_20161122-14_09_41.236.txt         34.539580         34.550584
98  thermal_20161122-14_09_41.276.txt         34.526881         34.541973
99  thermal_20161122-14_09_41.315.txt         34.525159         34.537595

    AvgTemp(72,95)  AvgTemp(24,32)
0        34.458716       34.577966
1        34.454174       34.622807
2        34.456102       34.543333
3        34.477656       34.553333
4        34.465766       34.550820
5        34.476937       34.521667
6        34.476630       34.622034
7        34.462138       34.511667
8        34.502500       34.619672
9        34.485893       34.519672
10       34.501089       34.610345
11       34.524954       34.593220
12       34.475906       34.622807
13       34.497222       34.624561
14       34.489174       34.608475
15       34.474955       34.546667
16       34.483630       34.664407
17       34.488727       34.618333
18       34.497288       34.643103
19       34.493648       34.615000
20       34.516667       34.606897
21       34.484409       34.562712
22       34.469245       34.505000
23       34.488172       34.545763
24       34.500722       34.549153
25       34.506082       34.556667
26       34.509273       34.537288
27       34.489150       34.567241
28       34.511372       34.603448
29       34.519337       34.562069
30       34.520545       34.491667
31       34.503571       34.500000
32       34.494494       34.523333
33       34.522645       34.605172
34       34.485868       34.460656
35       34.522628       34.579310
36       34.494565       34.579310
37       34.504182       34.567241
38       34.497292       34.570690
39       34.472662       34.473333
40       34.495985       34.551724
41       34.510420       34.516949
42       34.500000       34.550000
43       34.508484       34.596552
44       34.532727       34.549153
45       34.484079       34.454098
46       34.488139       34.494915
47       34.524910       34.586441
48       34.525136       34.584746
49       34.527536       34.596552
50       34.514493       34.567797
51       34.534000       34.562712
52       34.544096       34.603509
53       34.510364       34.628070
54       34.511191       34.589655
55       34.509800       34.574138
56       34.526384       34.622807
57       34.512681       34.555932
58       34.520545       34.603448
59       34.511581       34.596491
60       34.502347       34.612069
61       34.507818       34.661404
62       34.524638       34.618966
63       34.527422       34.613793
64       34.519419       34.624138
65       34.533213       34.651724
66       34.557685       34.713559
67       34.489170       34.577966
68       34.500719       34.657627
69       34.515315       34.680702
70       34.519238       34.605172
71       34.481172       34.620690
72       34.503540       34.577419
73       34.505216       34.677966
74       34.463428       34.518033
75       34.529189       34.724138
76       34.548457       34.706780
77       34.559893       34.710000
78       34.549189       34.737288
79       34.488434       34.694915
80       34.512633       34.674138
81       34.511871       34.652542
82       34.557603       34.728814
83       34.552166       34.710169
84       34.498944       34.524194
85       34.531351       34.591667
86       34.509302       34.605085
87       34.519435       34.563333
88       34.526773       34.503279
89       34.505759       34.646552
90       34.534568       34.485484
91       34.530823       34.534426
92       34.562254       34.639655
93       34.561191       34.650847
94       34.510835       34.673684
95       34.538530       34.572881
96       34.535273       34.608197
97       34.539750       34.710345
98       34.515780       34.659322
99       34.538959       34.665517

In [71]:
listOfStds = ['std(382,288)','std(191,144)', 'std(95,72)', 'std(32,24)']

In [72]:
folder_avg_joao = []
joao_std = []
for idx,i in enumerate(df_joao.columns.values[1:]):
    folder_avg_joao.append({i : np.average(df_joao[i])})    
    joao_std.append({listOfStds[idx]: np.std(df_joao[i])})

In [73]:
joao_std

[{'std(382,288)': 0.01771227188307697},
 {'std(191,144)': 0.015419612529255826},
 {'std(95,72)': 0.020030440028060644},
 {'std(32,24)': 0.0826130079801894}]

In [74]:
folder_avg_joao

[{'AvgTemp(382,288)': 34.34906264155141},
 {'AvgTemp(191,144)': 34.3502226982291},
 {'AvgTemp(95,72)': 34.36255076260202},
 {'AvgTemp(32,24)': 34.51013792753642}]

## Claudio df for 100 files with four down scales and average for each row at each size

In [16]:
os.chdir(r"C:\Users\hp\Videos\Step1-fixedDistance_avg,std\Folders\2016-11-22-14-23-08-Claudio_onlythermalthermal_image-txt")

In [75]:
claudio_files = []  #claudio 

for idx,file in enumerate(os.listdir()):
    with open(file)as f:
        text_file = np.loadtxt(f)
        text_file[text_file<32.0]=0
        text_file[text_file>37.0]=0
        cam_res1 = cv.resize(text_file, (191,144), interpolation = cv.INTER_NEAREST)
       
        #print(np.max(cam_res1), np.min(cam_res1[cam_res1 != 0 ]))
        
        
        cam_res2 = cv.resize(cam_res1, (95,72), interpolation = cv.INTER_NEAREST)
        cam_res3 = cv.resize(cam_res2, (32,24), interpolation = cv.INTER_NEAREST)
        #rint(np.max(cam_res3), np.min(cam_res3[cam_res3 != 0 ]))
        """"
        plt.imshow(text_file,cmap='jet')
        plt.show()
        plt.imshow(cam_res1,cmap='jet')
        plt.show()
        plt.imshow(cam_res2,cmap='jet')
        plt.show()
        plt.imshow(cam_res3,cmap='jet')
        plt.show()
        print()
        """
        
        claudio_files.append({"file_name":file,
                              "AvgTemp(382,288)": np.average(text_file[text_file != 0]),
                              "AvgTemp(191,144)": np.average(cam_res1[cam_res1 != 0]),
                              "AvgTemp(95,72)": np.average(cam_res2[cam_res2 != 0]),
                              "AvgTemp(32,24)": np.average(cam_res3[cam_res3 != 0])})
    if idx == 99:
        break

In [76]:
df_claudio = pd.DataFrame(claudio_files, columns = ['file_name',"AvgTemp(382,288)","AvgTemp(191,144)","AvgTemp(95,72)","AvgTemp(32,24)"])

In [77]:
df_claudio

,file_name,"AvgTemp(382,288)","AvgTemp(191,144)","AvgTemp(95,72)","AvgTemp(32,24)"
0,thermal_20161122-14_13_46.750.txt,34.363804,34.362176,34.401961,34.595062
1,thermal_20161122-14_13_46.785.txt,34.343402,34.345606,34.383567,34.489024
2,thermal_20161122-14_13_46.824.txt,34.340241,34.342957,34.358650,34.517284
3,thermal_20161122-14_13_46.860.txt,34.358668,34.358059,34.401266,34.545679
4,thermal_20161122-14_13_46.896.txt,34.348433,34.353717,34.388511,34.535000
...,...,...,...,...,...
95,thermal_20161122-14_13_50.572.txt,34.308287,34.320829,34.353314,34.334177
96,thermal_20161122-14_13_50.608.txt,34.310669,34.323435,34.353247,34.327848
97,thermal_20161122-14_13_50.647.txt,34.310501,34.326230,34.376890,34.307595
98,thermal_20161122-14_13_50.722.txt,34.310970,34.317014,34.338516,34.262500
99,thermal_20161122-14_13_50.757.txt,34.319824,34.321256,34.335971,34.332000

In [78]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(df_claudio)

                            file_name  AvgTemp(382,288)  AvgTemp(191,144)  \
0   thermal_20161122-14_13_46.750.txt         34.363804         34.362176
1   thermal_20161122-14_13_46.785.txt         34.343402         34.345606
2   thermal_20161122-14_13_46.824.txt         34.340241         34.342957
3   thermal_20161122-14_13_46.860.txt         34.358668         34.358059
4   thermal_20161122-14_13_46.896.txt         34.348433         34.353717
5   thermal_20161122-14_13_46.933.txt         34.349049         34.358180
6   thermal_20161122-14_13_46.973.txt         34.354705         34.359758
7   thermal_20161122-14_13_47.008.txt         34.328705         34.339687
8   thermal_20161122-14_13_47.044.txt         34.352162         34.356654
9   thermal_20161122-14_13_47.084.txt         34.353909         34.350605
10  thermal_20161122-14_13_47.121.txt         34.352959         34.364172
11  thermal_20161122-14_13_47.155.txt         34.328258         34.338483
12  thermal_20161122-14_13_47.191.txt         34.332929         34.335319
13  thermal_20161122-14_13_47.239.txt         34.331009         34.343958
14  thermal_20161122-14_13_47.272.txt         34.326195         34.333776
15  thermal_20161122-14_13_47.306.txt         34.333884         34.337600
16  thermal_20161122-14_13_47.346.txt         34.319996         34.324251
17  thermal_20161122-14_13_47.379.txt         34.331604         34.337513
18  thermal_20161122-14_13_47.420.txt         34.351250         34.363909
19  thermal_20161122-14_13_47.452.txt         34.339348         34.352256
20  thermal_20161122-14_13_47.493.txt         34.342868         34.350873
21  thermal_20161122-14_13_47.532.txt         34.343980         34.347012
22  thermal_20161122-14_13_47.563.txt         34.333252         34.342607
23  thermal_20161122-14_13_47.606.txt         34.335260         34.348525
24  thermal_20161122-14_13_47.639.txt         34.359334         34.361034
25  thermal_20161122-14_13_47.675.txt         34.359990         34.364606
26  thermal_20161122-14_13_47.712.txt         34.352461         34.373576
27  thermal_20161122-14_13_47.752.txt         34.356322         34.368635
28  thermal_20161122-14_13_47.788.txt         34.349784         34.354485
29  thermal_20161122-14_13_47.825.txt         34.341560         34.345822
30  thermal_20161122-14_13_47.865.txt         34.360702         34.363523
31  thermal_20161122-14_13_47.903.txt         34.358396         34.351471
32  thermal_20161122-14_13_47.971.txt         34.357773         34.352511
33  thermal_20161122-14_13_48.012.txt         34.356287         34.355690
34  thermal_20161122-14_13_48.087.txt         34.351035         34.343963
35  thermal_20161122-14_13_48.122.txt         34.335531         34.343506
36  thermal_20161122-14_13_48.162.txt         34.334601         34.331015
37  thermal_20161122-14_13_48.196.txt         34.342170         34.339313
38  thermal_20161122-14_13_48.231.txt         34.371161         34.369172
39  thermal_20161122-14_13_48.271.txt         34.354688         34.346821
40  thermal_20161122-14_13_48.312.txt         34.356592         34.347191
41  thermal_20161122-14_13_48.346.txt         34.345324         34.345372
42  thermal_20161122-14_13_48.379.txt         34.336788         34.342397
43  thermal_20161122-14_13_48.425.txt         34.351990         34.347423
44  thermal_20161122-14_13_48.497.txt         34.370204         34.365926
45  thermal_20161122-14_13_48.531.txt         34.366877         34.365847
46  thermal_20161122-14_13_48.570.txt         34.359169         34.359151
47  thermal_20161122-14_13_48.606.txt         34.365115         34.365940
48  thermal_20161122-14_13_48.639.txt         34.368762         34.359675
49  thermal_20161122-14_13_48.680.txt         34.355675         34.345803
50  thermal_20161122-14_13_48.724.txt         34.361099         34.348753
51  thermal_20161122-14_13_48.755.txt         34.362122         34.347281
52  thermal_20161122-14_13_48.794.txt         34.367074         34.360722
53  thermal_20161122-14_13_48.864.txt         34.385076         34.367320
54  thermal_20161122-14_13_48.904.txt         34.367827         34.355436
55  thermal_20161122-14_13_48.942.txt         34.368968         34.362045
56  thermal_20161122-14_13_48.975.txt         34.357350         34.348906
57  thermal_20161122-14_13_49.012.txt         34.340090         34.336886
58  thermal_20161122-14_13_49.050.txt         34.380155         34.376048
59  thermal_20161122-14_13_49.090.txt         34.368759         34.365276
60  thermal_20161122-14_13_49.159.txt         34.375421         34.371913
61  thermal_20161122-14_13_49.202.txt         34.376442         34.372885
62  thermal_20161122-14_13_49.236.txt         34.378287         34.368951
63  thermal_20161122-14_13_49.271.txt         34.378937         34.370596
64  thermal_20161122-14_13_49.311.txt         34.362731         34.367374
65  thermal_20161122-14_13_49.349.txt         34.373295         34.369399
66  thermal_20161122-14_13_49.386.txt         34.357733         34.358193
67  thermal_20161122-14_13_49.423.txt         34.359221         34.368537
68  thermal_20161122-14_13_49.459.txt         34.357170         34.355679
69  thermal_20161122-14_13_49.496.txt         34.346089         34.355462
70  thermal_20161122-14_13_49.534.txt         34.373110         34.368977
71  thermal_20161122-14_13_49.569.txt         34.381297         34.385779
72  thermal_20161122-14_13_49.614.txt         34.368394         34.362879
73  thermal_20161122-14_13_49.682.txt         34.363937         34.369523
74  thermal_20161122-14_13_49.722.txt         34.371729         34.374765
75  thermal_20161122-14_13_49.757.txt         34.365303         34.364626
76  thermal_20161122-14_13_49.792.txt         34.340770         34.340127
77  thermal_20161122-14_13_49.831.txt         34.329340         34.326730
78  thermal_20161122-14_13_49.868.txt         34.333747         34.323625
79  thermal_20161122-14_13_49.904.txt         34.336313         34.340275
80  thermal_20161122-14_13_49.941.txt         34.342035         34.338373
81  thermal_20161122-14_13_49.979.txt         34.335743         34.332133
82  thermal_20161122-14_13_50.051.txt         34.332611         34.330476
83  thermal_20161122-14_13_50.088.txt         34.333988         34.330666
84  thermal_20161122-14_13_50.129.txt         34.320824         34.320894
85  thermal_20161122-14_13_50.204.txt         34.347531         34.347569
86  thermal_20161122-14_13_50.237.txt         34.328949         34.323239
87  thermal_20161122-14_13_50.276.txt         34.350004         34.352760
88  thermal_20161122-14_13_50.312.txt         34.351435         34.352067
89  thermal_20161122-14_13_50.347.txt         34.343794         34.350386
90  thermal_20161122-14_13_50.389.txt         34.332769         34.344031
91  thermal_20161122-14_13_50.431.txt         34.342771         34.348982
92  thermal_20161122-14_13_50.460.txt         34.346348         34.355934
93  thermal_20161122-14_13_50.497.txt         34.322803         34.326648
94  thermal_20161122-14_13_50.541.txt         34.312461         34.316855
95  thermal_20161122-14_13_50.572.txt         34.308287         34.320829
96  thermal_20161122-14_13_50.608.txt         34.310669         34.323435
97  thermal_20161122-14_13_50.647.txt         34.310501         34.326230
98  thermal_20161122-14_13_50.722.txt         34.310970         34.317014
99  thermal_20161122-14_13_50.757.txt         34.319824         34.321256

    AvgTemp(95,72)  AvgTemp(32,24)
0        34.401961       34.595062
1        34.383567       34.489024
2        34.358650       34.517284
3        34.401266       34.545679
4        34.388511       34.535000
5        34.375983       34.586076
6        34.372462       34.537975
7        34.360894       34.584416
8        34.367270       34.611538
9        34.360000       34.565385
10       34.383939       34.624675
11       34.341690       34.614474
12       34.339014       34.598611
13       34.365439       34.583784
14       34.337902       34.607895
15       34.341480       34.653425
16       34.328873       34.612329
17       34.341737       34.546667
18       34.377279       34.540541
19       34.354533       34.582432
20       34.357223       34.556164
21       34.346429       34.602632
22       34.346154       34.563014
23       34.346835       34.550667
24       34.367778       34.602703
25       34.374131       34.600000
26       34.377115       34.637333
27       34.367688       34.602703
28       34.374581       34.608000
29       34.350975       34.590667
30       34.373464       34.573333
31       34.357843       34.552000
32       34.365546       34.530380
33       34.343593       34.524675
34       34.349226       34.491139
35       34.337482       34.481250
36       34.333853       34.531646
37       34.361932       34.520000
38       34.386017       34.534177
39       34.376090       34.582500
40       34.361851       34.491250
41       34.354635       34.517500
42       34.368324       34.508750
43       34.367606       34.512346
44       34.382303       34.544304
45       34.367922       34.539506
46       34.366760       34.507407
47       34.404348       34.553750
48       34.363916       34.523457
49       34.366432       34.498734
50       34.370687       34.516456
51       34.359327       34.491250
52       34.364755       34.511538
53       34.364485       34.536364
54       34.360420       34.528205
55       34.393069       34.574684
56       34.369902       34.522785
57       34.340393       34.505063
58       34.402101       34.584810
59       34.382535       34.545570
60       34.365417       34.496296
61       34.374790       34.556962
62       34.371910       34.480769
63       34.373853       34.553750
64       34.369620       34.589744
65       34.381601       34.574359
66       34.360845       34.532468
67       34.362973       34.551282
68       34.355882       34.521519
69       34.351685       34.524051
70       34.361560       34.476623
71       34.388456       34.545455
72       34.359637       34.513924
73       34.354798       34.533766
74       34.381058       34.548718
75       34.362219       34.502597
76       34.333333       34.471795
77       34.313184       34.433333
78       34.320733       34.390000
79       34.320451       34.376250
80       34.321800       34.378750
81       34.318847       34.386250
82       34.331294       34.406410
83       34.339716       34.385000
84       34.347701       34.419231
85       34.383095       34.482051
86       34.349288       34.380000
87       34.388936       34.446835
88       34.388920       34.395000
89       34.381883       34.380000
90       34.397674       34.403797
91       34.390000       34.385000
92       34.390754       34.413924
93       34.363467       34.389744
94       34.351580       34.343038
95       34.353314       34.334177
96       34.353247       34.327848
97       34.376890       34.307595
98       34.338516       34.262500
99       34.335971       34.332000

In [79]:
listOfStds

['std(382,288)', 'std(191,144)', 'std(95,72)', 'std(32,24)']

In [80]:
df_claudio.columns.values[1:]

array(['AvgTemp(382,288)', 'AvgTemp(191,144)', 'AvgTemp(95,72)',
       'AvgTemp(32,24)'], dtype=object)

In [81]:
np.average(df_claudio['AvgTemp(382,288)'])

34.34906264155141

In [82]:
folder_avg_claudio = []
claudio_std = []
for idx,i in enumerate(df_claudio.columns.values[1:]):
    folder_avg_claudio.append({i : np.average(df_claudio[i])})
    claudio_std.append({listOfStds[idx]: np.std(df_claudio[i])})

In [83]:
folder_avg_claudio

[{'AvgTemp(382,288)': 34.34906264155141},
 {'AvgTemp(191,144)': 34.3502226982291},
 {'AvgTemp(95,72)': 34.36255076260202},
 {'AvgTemp(32,24)': 34.51013792753642}]

In [84]:
claudio_std

[{'std(382,288)': 0.01771227188307697},
 {'std(191,144)': 0.015419612529255826},
 {'std(95,72)': 0.020030440028060644},
 {'std(32,24)': 0.0826130079801894}]

### Anestis df for 100 files with four down scales and average for each row at each size

In [30]:
os.chdir(r"C:\Users\hp\Videos\Step1-fixedDistance_avg,std\Folders\2016-11-22-14-13-46-anestis_onlythermalthermal_image-txt")

In [85]:
anestis_files = []  #claudio 

for idx,file in enumerate(os.listdir()):
    with open(file)as f:
        text_file = np.loadtxt(f)
        text_file[text_file<32.0]=0
        text_file[text_file>37.0]=0
        cam_res1 = cv.resize(text_file, (191,144), interpolation = cv.INTER_NEAREST)
        
        #print(np.max(cam_res1), np.min(cam_res1[cam_res1 != 0 ]))
        
        
        cam_res2 = cv.resize(cam_res1, (95,72), interpolation = cv.INTER_NEAREST)
        cam_res3 = cv.resize(cam_res2, (32,24), interpolation = cv.INTER_NEAREST)
        #rint(np.max(cam_res3), np.min(cam_res3[cam_res3 != 0 ]))
        """"
        plt.imshow(text_file,cmap='jet')
        plt.show()
        plt.imshow(cam_res1,cmap='jet')
        plt.show()
        plt.imshow(cam_res2,cmap='jet')
        plt.show()
        plt.imshow(cam_res3,cmap='jet')
        plt.show()
        print()
        """
        
        
        anestis_files.append({"file_name":file,
                              "AvgTemp(382,288)": np.average(text_file[text_file != 0]),
                              "AvgTemp(191,144)": np.average(cam_res1[cam_res1 != 0]),
                              "AvgTemp(95,72)": np.average(cam_res2[cam_res2 != 0]),
                              "AvgTemp(32,24)": np.average(cam_res3[cam_res3 != 0])})
    if idx == 99:
        break

In [86]:
df_anestis = pd.DataFrame(anestis_files, columns = ['file_name',"AvgTemp(382,288)","AvgTemp(191,144)","AvgTemp(95,72)","AvgTemp(32,24)"])

In [87]:
df_anestis

,file_name,"AvgTemp(382,288)","AvgTemp(191,144)","AvgTemp(95,72)","AvgTemp(32,24)"
0,thermal_20161122-14_13_46.750.txt,34.363804,34.362176,34.401961,34.595062
1,thermal_20161122-14_13_46.785.txt,34.343402,34.345606,34.383567,34.489024
2,thermal_20161122-14_13_46.824.txt,34.340241,34.342957,34.358650,34.517284
3,thermal_20161122-14_13_46.860.txt,34.358668,34.358059,34.401266,34.545679
4,thermal_20161122-14_13_46.896.txt,34.348433,34.353717,34.388511,34.535000
...,...,...,...,...,...
95,thermal_20161122-14_13_50.572.txt,34.308287,34.320829,34.353314,34.334177
96,thermal_20161122-14_13_50.608.txt,34.310669,34.323435,34.353247,34.327848
97,thermal_20161122-14_13_50.647.txt,34.310501,34.326230,34.376890,34.307595
98,thermal_20161122-14_13_50.722.txt,34.310970,34.317014,34.338516,34.262500
99,thermal_20161122-14_13_50.757.txt,34.319824,34.321256,34.335971,34.332000

In [88]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(df_anestis)

                            file_name  AvgTemp(382,288)  AvgTemp(191,144)  \
0   thermal_20161122-14_13_46.750.txt         34.363804         34.362176
1   thermal_20161122-14_13_46.785.txt         34.343402         34.345606
2   thermal_20161122-14_13_46.824.txt         34.340241         34.342957
3   thermal_20161122-14_13_46.860.txt         34.358668         34.358059
4   thermal_20161122-14_13_46.896.txt         34.348433         34.353717
5   thermal_20161122-14_13_46.933.txt         34.349049         34.358180
6   thermal_20161122-14_13_46.973.txt         34.354705         34.359758
7   thermal_20161122-14_13_47.008.txt         34.328705         34.339687
8   thermal_20161122-14_13_47.044.txt         34.352162         34.356654
9   thermal_20161122-14_13_47.084.txt         34.353909         34.350605
10  thermal_20161122-14_13_47.121.txt         34.352959         34.364172
11  thermal_20161122-14_13_47.155.txt         34.328258         34.338483
12  thermal_20161122-14_13_47.191.txt         34.332929         34.335319
13  thermal_20161122-14_13_47.239.txt         34.331009         34.343958
14  thermal_20161122-14_13_47.272.txt         34.326195         34.333776
15  thermal_20161122-14_13_47.306.txt         34.333884         34.337600
16  thermal_20161122-14_13_47.346.txt         34.319996         34.324251
17  thermal_20161122-14_13_47.379.txt         34.331604         34.337513
18  thermal_20161122-14_13_47.420.txt         34.351250         34.363909
19  thermal_20161122-14_13_47.452.txt         34.339348         34.352256
20  thermal_20161122-14_13_47.493.txt         34.342868         34.350873
21  thermal_20161122-14_13_47.532.txt         34.343980         34.347012
22  thermal_20161122-14_13_47.563.txt         34.333252         34.342607
23  thermal_20161122-14_13_47.606.txt         34.335260         34.348525
24  thermal_20161122-14_13_47.639.txt         34.359334         34.361034
25  thermal_20161122-14_13_47.675.txt         34.359990         34.364606
26  thermal_20161122-14_13_47.712.txt         34.352461         34.373576
27  thermal_20161122-14_13_47.752.txt         34.356322         34.368635
28  thermal_20161122-14_13_47.788.txt         34.349784         34.354485
29  thermal_20161122-14_13_47.825.txt         34.341560         34.345822
30  thermal_20161122-14_13_47.865.txt         34.360702         34.363523
31  thermal_20161122-14_13_47.903.txt         34.358396         34.351471
32  thermal_20161122-14_13_47.971.txt         34.357773         34.352511
33  thermal_20161122-14_13_48.012.txt         34.356287         34.355690
34  thermal_20161122-14_13_48.087.txt         34.351035         34.343963
35  thermal_20161122-14_13_48.122.txt         34.335531         34.343506
36  thermal_20161122-14_13_48.162.txt         34.334601         34.331015
37  thermal_20161122-14_13_48.196.txt         34.342170         34.339313
38  thermal_20161122-14_13_48.231.txt         34.371161         34.369172
39  thermal_20161122-14_13_48.271.txt         34.354688         34.346821
40  thermal_20161122-14_13_48.312.txt         34.356592         34.347191
41  thermal_20161122-14_13_48.346.txt         34.345324         34.345372
42  thermal_20161122-14_13_48.379.txt         34.336788         34.342397
43  thermal_20161122-14_13_48.425.txt         34.351990         34.347423
44  thermal_20161122-14_13_48.497.txt         34.370204         34.365926
45  thermal_20161122-14_13_48.531.txt         34.366877         34.365847
46  thermal_20161122-14_13_48.570.txt         34.359169         34.359151
47  thermal_20161122-14_13_48.606.txt         34.365115         34.365940
48  thermal_20161122-14_13_48.639.txt         34.368762         34.359675
49  thermal_20161122-14_13_48.680.txt         34.355675         34.345803
50  thermal_20161122-14_13_48.724.txt         34.361099         34.348753
51  thermal_20161122-14_13_48.755.txt         34.362122         34.347281
52  thermal_20161122-14_13_48.794.txt         34.367074         34.360722
53  thermal_20161122-14_13_48.864.txt         34.385076         34.367320
54  thermal_20161122-14_13_48.904.txt         34.367827         34.355436
55  thermal_20161122-14_13_48.942.txt         34.368968         34.362045
56  thermal_20161122-14_13_48.975.txt         34.357350         34.348906
57  thermal_20161122-14_13_49.012.txt         34.340090         34.336886
58  thermal_20161122-14_13_49.050.txt         34.380155         34.376048
59  thermal_20161122-14_13_49.090.txt         34.368759         34.365276
60  thermal_20161122-14_13_49.159.txt         34.375421         34.371913
61  thermal_20161122-14_13_49.202.txt         34.376442         34.372885
62  thermal_20161122-14_13_49.236.txt         34.378287         34.368951
63  thermal_20161122-14_13_49.271.txt         34.378937         34.370596
64  thermal_20161122-14_13_49.311.txt         34.362731         34.367374
65  thermal_20161122-14_13_49.349.txt         34.373295         34.369399
66  thermal_20161122-14_13_49.386.txt         34.357733         34.358193
67  thermal_20161122-14_13_49.423.txt         34.359221         34.368537
68  thermal_20161122-14_13_49.459.txt         34.357170         34.355679
69  thermal_20161122-14_13_49.496.txt         34.346089         34.355462
70  thermal_20161122-14_13_49.534.txt         34.373110         34.368977
71  thermal_20161122-14_13_49.569.txt         34.381297         34.385779
72  thermal_20161122-14_13_49.614.txt         34.368394         34.362879
73  thermal_20161122-14_13_49.682.txt         34.363937         34.369523
74  thermal_20161122-14_13_49.722.txt         34.371729         34.374765
75  thermal_20161122-14_13_49.757.txt         34.365303         34.364626
76  thermal_20161122-14_13_49.792.txt         34.340770         34.340127
77  thermal_20161122-14_13_49.831.txt         34.329340         34.326730
78  thermal_20161122-14_13_49.868.txt         34.333747         34.323625
79  thermal_20161122-14_13_49.904.txt         34.336313         34.340275
80  thermal_20161122-14_13_49.941.txt         34.342035         34.338373
81  thermal_20161122-14_13_49.979.txt         34.335743         34.332133
82  thermal_20161122-14_13_50.051.txt         34.332611         34.330476
83  thermal_20161122-14_13_50.088.txt         34.333988         34.330666
84  thermal_20161122-14_13_50.129.txt         34.320824         34.320894
85  thermal_20161122-14_13_50.204.txt         34.347531         34.347569
86  thermal_20161122-14_13_50.237.txt         34.328949         34.323239
87  thermal_20161122-14_13_50.276.txt         34.350004         34.352760
88  thermal_20161122-14_13_50.312.txt         34.351435         34.352067
89  thermal_20161122-14_13_50.347.txt         34.343794         34.350386
90  thermal_20161122-14_13_50.389.txt         34.332769         34.344031
91  thermal_20161122-14_13_50.431.txt         34.342771         34.348982
92  thermal_20161122-14_13_50.460.txt         34.346348         34.355934
93  thermal_20161122-14_13_50.497.txt         34.322803         34.326648
94  thermal_20161122-14_13_50.541.txt         34.312461         34.316855
95  thermal_20161122-14_13_50.572.txt         34.308287         34.320829
96  thermal_20161122-14_13_50.608.txt         34.310669         34.323435
97  thermal_20161122-14_13_50.647.txt         34.310501         34.326230
98  thermal_20161122-14_13_50.722.txt         34.310970         34.317014
99  thermal_20161122-14_13_50.757.txt         34.319824         34.321256

    AvgTemp(95,72)  AvgTemp(32,24)
0        34.401961       34.595062
1        34.383567       34.489024
2        34.358650       34.517284
3        34.401266       34.545679
4        34.388511       34.535000
5        34.375983       34.586076
6        34.372462       34.537975
7        34.360894       34.584416
8        34.367270       34.611538
9        34.360000       34.565385
10       34.383939       34.624675
11       34.341690       34.614474
12       34.339014       34.598611
13       34.365439       34.583784
14       34.337902       34.607895
15       34.341480       34.653425
16       34.328873       34.612329
17       34.341737       34.546667
18       34.377279       34.540541
19       34.354533       34.582432
20       34.357223       34.556164
21       34.346429       34.602632
22       34.346154       34.563014
23       34.346835       34.550667
24       34.367778       34.602703
25       34.374131       34.600000
26       34.377115       34.637333
27       34.367688       34.602703
28       34.374581       34.608000
29       34.350975       34.590667
30       34.373464       34.573333
31       34.357843       34.552000
32       34.365546       34.530380
33       34.343593       34.524675
34       34.349226       34.491139
35       34.337482       34.481250
36       34.333853       34.531646
37       34.361932       34.520000
38       34.386017       34.534177
39       34.376090       34.582500
40       34.361851       34.491250
41       34.354635       34.517500
42       34.368324       34.508750
43       34.367606       34.512346
44       34.382303       34.544304
45       34.367922       34.539506
46       34.366760       34.507407
47       34.404348       34.553750
48       34.363916       34.523457
49       34.366432       34.498734
50       34.370687       34.516456
51       34.359327       34.491250
52       34.364755       34.511538
53       34.364485       34.536364
54       34.360420       34.528205
55       34.393069       34.574684
56       34.369902       34.522785
57       34.340393       34.505063
58       34.402101       34.584810
59       34.382535       34.545570
60       34.365417       34.496296
61       34.374790       34.556962
62       34.371910       34.480769
63       34.373853       34.553750
64       34.369620       34.589744
65       34.381601       34.574359
66       34.360845       34.532468
67       34.362973       34.551282
68       34.355882       34.521519
69       34.351685       34.524051
70       34.361560       34.476623
71       34.388456       34.545455
72       34.359637       34.513924
73       34.354798       34.533766
74       34.381058       34.548718
75       34.362219       34.502597
76       34.333333       34.471795
77       34.313184       34.433333
78       34.320733       34.390000
79       34.320451       34.376250
80       34.321800       34.378750
81       34.318847       34.386250
82       34.331294       34.406410
83       34.339716       34.385000
84       34.347701       34.419231
85       34.383095       34.482051
86       34.349288       34.380000
87       34.388936       34.446835
88       34.388920       34.395000
89       34.381883       34.380000
90       34.397674       34.403797
91       34.390000       34.385000
92       34.390754       34.413924
93       34.363467       34.389744
94       34.351580       34.343038
95       34.353314       34.334177
96       34.353247       34.327848
97       34.376890       34.307595
98       34.338516       34.262500
99       34.335971       34.332000

In [89]:
anestis_avg_values = []

In [90]:
folder_avg_anestis = []
anestis_std = []
for idx,i in enumerate(df_anestis.columns.values[1:]):
    folder_avg_anestis.append({i : np.average(df_anestis[i])})
    anestis_std.append({listOfStds[idx]: np.std(df_anestis[i])})

In [91]:
anestis_std

[{'std(382,288)': 0.01771227188307697},
 {'std(191,144)': 0.015419612529255826},
 {'std(95,72)': 0.020030440028060644},
 {'std(32,24)': 0.0826130079801894}]

### Average per row for three folders at four different scales

In [92]:
df_claudio['AvgTemp(382,288)'].mean(),df_joao['AvgTemp(382,288)'].mean(), df_anestis['AvgTemp(382,288)'].mean()

(34.349062641551384, 34.349062641551384, 34.349062641551384)

In [93]:
pd.DataFrame({"Name": ['claudio','Joao','Anestis'],
             'AvgTemp(382,288)':[34.49699525947614,34.50318318575525, 34.349062641551384],
             'AvgTemp(191,144)':[34.49785087067999,34.50989892068498,34.35012920387215],
             'AvgTemp(95,72)':[34.500394847807605,34.50884268714953,34.3626544902959],
             'AvgTemp(32,24)':[34.55686197967155,34.59467334822509,34.509298278088856]})

      Name  AvgTemp(382,288)  AvgTemp(191,144)  AvgTemp(95,72)  AvgTemp(32,24)
0  claudio         34.496995         34.497851       34.500395       34.556862
1     Joao         34.503183         34.509899       34.508843       34.594673
2  Anestis         34.349063         34.350129       34.362654       34.509298

In [94]:
test = pd.DataFrame({"Name": ['claudio','Joao','Anestis'],
           'AvgTemp(382,288)':[34.49699525947614,34.50318318575525, 34.349062641551384],
           'AvgTemp(191,144)':[34.49785087067999,34.50989892068498,34.35012920387215],
           'AvgTemp(95,72)':[34.500394847807605,34.50884268714953,34.3626544902959],
           'AvgTemp(32,24)':[34.55686197967155,34.59467334822509,34.509298278088856]})
test

      Name  AvgTemp(382,288)  AvgTemp(191,144)  AvgTemp(95,72)  AvgTemp(32,24)
0  claudio         34.496995         34.497851       34.500395       34.556862
1     Joao         34.503183         34.509899       34.508843       34.594673
2  Anestis         34.349063         34.350129       34.362654       34.509298

In [96]:
test['std'] = np.std(test[['AvgTemp(382,288)','AvgTemp(191,144)','AvgTemp(95,72)','AvgTemp(32,24)']],axis=1)

In [97]:
test

,Name,"AvgTemp(382,288)","AvgTemp(191,144)","AvgTemp(95,72)","AvgTemp(32,24)",std
0,claudio,34.496995,34.497851,34.500395,34.556862,0.025340
1,Joao,34.503183,34.509899,34.508843,34.594673,0.037916
2,Anestis,34.349063,34.350129,34.362654,34.509298,0.067480

In [98]:
np.std([34.497851, 34.500395, 34.556862])

0.027238233231171336

### Standard deviation for three folders at four different scales

In [99]:
claudio_std, joao_std, anestis_std

([{'std(382,288)': 0.01771227188307697},
  {'std(191,144)': 0.015419612529255826},
  {'std(95,72)': 0.020030440028060644},
  {'std(32,24)': 0.0826130079801894}],
 [{'std(382,288)': 0.01771227188307697},
  {'std(191,144)': 0.015419612529255826},
  {'std(95,72)': 0.020030440028060644},
  {'std(32,24)': 0.0826130079801894}],
 [{'std(382,288)': 0.01771227188307697},
  {'std(191,144)': 0.015419612529255826},
  {'std(95,72)': 0.020030440028060644},
  {'std(32,24)': 0.0826130079801894}])

In [100]:
pd.DataFrame({"Name":
              ['claudio','Joao','Anestis'],
              'std(382,288)': [0.02131936265414212,0.017991776644567758,0.01771227188307697]
            , 'std(191,144)':[0.01886000410442223, 0.018540647118231956,0.015371547305321627]\
            , 'std(95,72)':[0.028265353490643932, 0.024646379041047137, 0.019958006175345336 ]\
            , 'std(32,24)':[0.08999542765363515, 0.06283265046011105, 0.08263072582103158]})

      Name  std(382,288)  std(191,144)  std(95,72)  std(32,24)
0  claudio      0.021319      0.018860    0.028265    0.089995
1     Joao      0.017992      0.018541    0.024646    0.062833
2  Anestis      0.017712      0.015372    0.019958    0.082631